import { Toaster } from "@/components/ui/sonner";
import QueryProviderWrapper from "@/components/wrappers/query-provider";
import type { Metadata } from "next";
import { Lexend_Deca } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/wrappers/theme-provider";

const lexend = Lexend_Deca({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
    <body className={`${lexend.className} min-h-screen  antialiased`}>
      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <QueryProviderWrapper>
              {children}
              <Toaster richColors position="bottom-right" />
            </QueryProviderWrapper>
          </ThemeProvider>
    </body>
  </html>
  );
}
