import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { Lexend_Deca } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import QueryProviderWrapper from "@/components/wrappers/query-provider";
import { SessionProvider } from "next-auth/react";

const lexend = Lexend_Deca({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${lexend.className} min-h-screen  antialiased`}>
        <QueryProviderWrapper>
          <SessionProvider>
            {/* <Navbar /> */}
            {children}
          </SessionProvider>
          <Toaster richColors position="bottom-right" />
        </QueryProviderWrapper>
      </body>
    </html>
  );
}
